version: '3.8'

services:
  app:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    volumes:
      - ./src:/app/src
      - ./config:/app/config

  mysql:
    image: mysql:8.0
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
  
networks:
  default:
    name: modular-integration-system-network