name: Build und Test

# Verbesserte Berechtigungen
permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Node.js Setup
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Clean Install
        run: |
          rm -f package-lock.json
          npm install
      
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            package-lock.json
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

  build:
    needs: setup
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            package-lock.json
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
      
      - name: Build
        run: npm run build
        
      - name: Cache Build Output
        uses: actions/cache@v3
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ github.sha }}

  test:
    needs: build
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            package-lock.json
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
      
      - name: Run Tests
        run: npm test
      
      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7