name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Clear npm cache and remove existing files
      run: |
        npm cache clean --force
        rm -f package-lock.json
        rm -rf node_modules
    
    - name: Install dependencies
      run: |
        npm install
        npm run build --if-present
    
    - name: Run tests
      run: npm test --if-present

  lint:
    runs-on: ubuntu-24.04
    needs: build

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run linting
      run: npm run lint --if-present

  security:
    runs-on: ubuntu-24.04
    needs: build

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run security audit
      run: npm audit
      continue-on-error: true