name: Build und Test

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write
  security-events: write  # Für CodeQL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * 0'  # Wöchentlicher Scan

jobs:
  analyze:
    name: CodeQL Analyze
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        language: [ 'typescript' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"

  setup:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Node.js Setup
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Clean Install
        run: |
          rm -f package-lock.json
          npm install
      
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            package-lock.json
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

  build:
    needs: setup
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      
      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            package-lock.json
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
      
      - name: Build
        run: npm run build
        
      - name: Cache Build Output
        uses: actions/cache@v4
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ github.sha }}

  test:
    needs: build
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      
      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            package-lock.json
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
      
      - name: Run Tests
        run: npm test
      
      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7

  security:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Security Audit
        run: npm audit
        continue-on-error: true  # Damit der Build nicht abbricht
      
      - name: Run License Check
        run: npx license-checker --production --json > licenses.json
        continue-on-error: true