name: Build und Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Node.js Setup
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Install Dependencies
        run: |
          npm install
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add package-lock.json
          git commit -m "chore: Update package-lock.json" || true
          git push || true
        
      - name: Build
        run: npm run build
        
      - name: Test
        run: npm test