name: Basic Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install

    - name: Add TypeScript configuration
      run: |
        echo '{
          "compilerOptions": {
            "target": "es2020",
            "module": "commonjs",
            "outDir": "./dist",
            "rootDir": "./src",
            "strict": true,
            "esModuleInterop": true,
            "skipLibCheck": true,
            "forceConsistentCasingInFileNames": true,
            "experimentalDecorators": true,
            "emitDecoratorMetadata": true
          },
          "include": ["src/**/*"],
          "exclude": ["node_modules", "**/*.spec.ts"]
        }' > tsconfig.json

    - name: Build
      run: |
        npm run build