name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    # F체hre zuerst eine regul채re Installation durch, wenn keine package-lock.json existiert
    - name: Generate package-lock.json if needed
      run: |
        if [ ! -f package-lock.json ]; then
          echo "Generating new package-lock.json..."
          rm -rf node_modules
          npm install --package-lock-only
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package-lock.json
          git commit -m "chore: update package-lock.json [skip ci]" || echo "No changes to commit"
          git push
        fi
    
    # Dann f체hre npm ci f체r die saubere Installation durch
    - name: Clean Install Dependencies
      run: npm ci
      
    - name: Run Linter
      run: npm run lint
      
    - name: Build
      run: npm run build
      
    - name: Test
      run: npm test