name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Verify npm cache
      run: |
        npm config get cache
        ls -la ~/.npm
    
    - name: Install dependencies
      run: |
        if [ ! -f package-lock.json ]; then
          npm install
          npm install --package-lock-only
        fi
        npm ci
    
    - name: Build
      run: npm run build
    
    - name: Run tests
      run: npm test
    
    - name: Debug information
      run: |
        node --version
        npm --version
        npm config list