name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 1'  # Jeden Montag
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Check for Updates
        id: ncu
        run: |
          npm install -g npm-check-updates
          ncu -u
          if [[ -n $(git status -s) ]]; then
            echo "updates_available=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Create Pull Request
        if: steps.ncu.outputs.updates_available == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore(deps): Update dependencies"
          title: "⬆️ Update Dependencies"
          body: |
            Automated dependency updates.
            
            Please review the changes and merge if all tests pass.
          branch: "deps/update"
          delete-branch: true
          labels: |
            dependencies
            automated pr
            
  security-audit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Install Snyk
        run: npm install -g snyk
        
      - name: Snyk Auth
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        
      - name: Run Snyk Test
        run: snyk test
        continue-on-error: true
        
      - name: Run Snyk Monitor
        run: snyk monitor
        continue-on-error: true