name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Clear package files
      run: |
        rm -f package-lock.json
        rm -rf node_modules

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build --if-present

    - name: Test
      run: npm test --if-present