name: Main CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Create tsconfig.json
        run: |
          echo '{
            "compilerOptions": {
              "target": "es2020",
              "module": "commonjs",
              "lib": ["es2020"],
              "outDir": "./dist",
              "rootDir": "./src",
              "strict": true,
              "esModuleInterop": true,
              "skipLibCheck": true,
              "forceConsistentCasingInFileNames": true,
              "experimentalDecorators": true,
              "emitDecoratorMetadata": true,
              "declaration": true,
              "moduleResolution": "node"
            },
            "include": ["src/**/*"],
            "exclude": ["node_modules", "**/*.spec.ts"]
          }' > tsconfig.json

      - name: Install dependencies
        run: npm ci || (rm -rf node_modules package-lock.json && npm install)

      - name: Build
        run: npm run build

  analyze:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: typescript
      - uses: github/codeql-action/analyze@v3